In [8]:
import numpy as np
a=np.array([1,2,4])
a

array([1, 2, 4])

In [9]:
a.shape

(3,)

In [10]:
import numpy as np
a=np.array([[1,2,4],[3,5,6]])
a

array([[1, 2, 4],
       [3, 5, 6]])

In [11]:
a.shape

(2, 3)

In [3]:
import numpy as np
a=np.array([[[1,2,4],[3,5,6],[8,9,0]]])
a

array([[[1, 2, 4],
        [3, 5, 6],
        [8, 9, 0]]])

In [4]:
a*2

array([[[ 2,  4,  8],
        [ 6, 10, 12],
        [16, 18,  0]]])

In [5]:
a+2

array([[[ 3,  4,  6],
        [ 5,  7,  8],
        [10, 11,  2]]])

In [6]:
a.shape

(1, 3, 3)

In [13]:
import numpy as np
n=np.arange(1,10,2)
n

array([1, 3, 5, 7, 9])

In [14]:
import numpy as np
n=np.arange(1,10)
n

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
import numpy as np
a=np.array([[1,2,4],[3,5,6]])
a
b=np.array(a)
b

array([[1, 2, 4],
       [3, 5, 6]])

In [21]:
c=a
c

array([[1, 2, 4],
       [3, 5, 6]])

In [20]:
a.ndim


2

In [22]:
a.dtype


dtype('int32')

In [24]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [32]:
np.empty((2,1))

array([[3.18488605e-011],
       [1.93431056e+165]])

In [38]:
np.empty((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
np.empty([2,2])  #The empty creates an array whose initial content is random
 #and depends on the state of the memory.

array([[6.95328962e-310, 1.43659115e-311],
       [6.69953016e-321, 1.43659115e-311]])

In [41]:
np.empty_like((2,3))

array([-1998362383,  1055193269])

In [50]:
import numpy as np
a=([1,2,4],[3,5,6])#numpy.asarray()function is used when we want to convert input to an array. Input can be lists, lists of tuples,
s=np.asarray(a,dtype=np.float64)  #tuples, tuples of tuples, tuples of lists and arrays.
s

array([[1., 2., 4.],
       [3., 5., 6.]])

In [69]:
import numpy as np
a=np.arange(2,10).reshape(2,4).astype(float)
a

array([[2., 3., 4., 5.],
       [6., 7., 8., 9.]])

In [90]:
import numpy as np
a=np.arange(2,10,dtype=float).reshape(2,4)
a

array([[2., 3., 4., 5.],
       [6., 7., 8., 9.]])

In [91]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. versionad

In [92]:
help(np.ones_like)

Help on _ArrayFunctionDispatcher in module numpy:

ones_like(a, dtype=None, order='K', subok=True, shape=None)
    Return an array of ones with the same shape and type as a given array.
    
    Parameters
    ----------
    a : array_like
        The shape and data-type of `a` define these same attributes of
        the returned array.
    dtype : data-type, optional
        Overrides the data type of the result.
    
        .. versionadded:: 1.6.0
    order : {'C', 'F', 'A', or 'K'}, optional
        Overrides the memory layout of the result. 'C' means C-order,
        'F' means F-order, 'A' means 'F' if `a` is Fortran contiguous,
        'C' otherwise. 'K' means match the layout of `a` as closely
        as possible.
    
        .. versionadded:: 1.6.0
    subok : bool, optional.
        If True, then the newly created array will use the sub-class
        type of `a`, otherwise it will be a base-class array. Defaults
        to True.
    shape : int or sequence of ints, optional.


In [93]:
import numpy as np
a=np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [94]:
b=np.ones_like(a)
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [95]:
import numpy as np
a=np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [96]:
b=np.zeros_like(a)  # Instead of taking a shape this function takes an array a
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [99]:
import numpy as np
a=np.full((2,3),(3,2,1),dtype=float)
a

array([[3., 2., 1.],
       [3., 2., 1.]])

In [109]:
#full_like() function is used to create an array with the same shape as
#an existing array and fill it with a specific value.
import numpy as np
a=np.arange(2,11,dtype=float).reshape(3,3)
a
b=np.full_like(a,(5,6,9),dtype=int)
b

array([[5, 6, 9],
       [5, 6, 9],
       [5, 6, 9]])

In [117]:
e=np.eye(2,3,k=2)
e


array([[0., 0., 1.],
       [0., 0., 0.]])

In [112]:
import numpy as np

# An array with 3 rows with with the ones starting at the index i.e fron the second column
myarray = np.eye(3, k=1)

print(myarray)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [128]:
#S="2"
a=np.identity(3,dtype=int)
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])