In [1]:
import numpy as np
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
a.dtype

dtype('int32')

In [4]:
b=a.astype(np.float64)
b

array([1., 2., 3., 4.])

In [5]:
b.dtype

dtype('float64')

In [11]:
str=a.astype(np.string_)
str

array([b'1', b'2', b'3', b'4'], dtype='|S11')

In [6]:
c=np.array(["1","2","3","4"])
c

array(['1', '2', '3', '4'], dtype='<U1')

In [7]:
d=c.astype(np.int32)
d

array([1, 2, 3, 4])

In [19]:
arr1=np.array([[1,2,3.],[7,8.,9]])
arr2=np.array([[4.,3,2],[10,6.,7]])
arr1
arr2

array([[ 4.,  3.,  2.],
       [10.,  6.,  7.]])

In [20]:
arr2>arr1

array([[ True,  True, False],
       [ True, False, False]])

In [23]:

arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr[3] #indexng

4

In [25]:
arr[2:7] #slicing

array([3, 4, 5, 6, 7])

In [27]:
arr[4:7]=8
arr

array([1, 2, 3, 4, 8, 8, 8, 8, 9])

In [28]:
slice_arr=arr[4:9]
slice_arr

array([8, 8, 8, 8, 9])

In [29]:
slice_arr[1]=4
slice_arr

array([8, 4, 8, 8, 9])

In [31]:
slice_arr[:]=99
arr

array([ 1,  2,  3,  4, 99, 99, 99, 99, 99])

In [32]:
slice_arr

array([99, 99, 99, 99, 99])

In [39]:
cp=slice_arr.copy()  #a copy and a view of an array is that the copy is a new array,
#and the view is just a view of the original array.
cp

array([99, 46, 46, 99, 99])

In [36]:
cp[1:3]=46
cp

array([99, 46, 46, 99, 99])

In [38]:
slice_arr.view()  #copy owns the data and any changes made to the copy will not affect original array,
#and any changes made to the original array will not affect the copy.
slice_arr

array([99, 46, 46, 99, 99])

In [41]:
c[1]=11
c

array([99, 11, 46, 99, 99])

In [42]:
arr

array([ 1,  2,  3,  4, 99, 11, 46, 99, 99])