In [152]:
import numpy as np
k=np.array([1,2,3,4,5])
k

array([1, 2, 3, 4, 5])

In [2]:
type(k)

numpy.ndarray

In [134]:
k.ndim

1

In [149]:
k.dtype

dtype('int32')

In [156]:
k.size  # size means length

5

In [153]:
k.itemsize     # itemsize means size of the each element

4

In [7]:
k[2]

3

In [8]:
k[:3]

array([1, 2, 3])

In [10]:
k[:4:2]

array([1, 3])

In [11]:
k.sum()

10

In [12]:
w=[5,6,7]
w


[5, 6, 7]

In [56]:
import numpy as np
k=np.array([1,2,3,4])
w=np.array([5,6,7,8])
np.dot([k,w])


TypeError: dot() missing 1 required positional argument: 'b'

In [1]:
import numpy as np
k=np.array([1,2,3,4])
w=np.array([5,6,7,8])
np.dot(k,w)


70

In [2]:
import numpy as np
k=np.array([1,2,3,4])
w=np.array([5,6,7,8])
k==w


array([False, False, False, False])

In [3]:
import numpy as np
k=np.array([1,2,3,4])
w=np.array([5,6,7,8])
k!=w


array([ True,  True,  True,  True])

In [55]:
import numpy as np`

k=np.array([1,2,3,4])
w=np.array([5,6,7,8])
(k*w).sum()

70

In [54]:
import numpy as np
k=np.array([1,2,3,4])
w=np.array([5,6,7,8])
np.dot([k,w])

TypeError: dot() missing 1 required positional argument: 'b'

In [4]:
import numpy as np
k=np.array([1,2,3,4])
w=np.array([5,6,7,8])
k>=w


array([False, False, False, False])

In [5]:
import numpy as np
k=np.array([1,2,3,4])
w=np.array([5,6,7,8])
k<=w


array([ True,  True,  True,  True])

In [6]:
import numpy as np
k=np.array([1,2,3,4])
w=np.array([5,6,7,8])
k==w.sum()


array([False, False, False, False])

In [21]:
(k*w).sum()

70

In [22]:
k.shape

(4,)

In [23]:
np.matmul(k,w)

70

In [24]:
k@w

70

In [26]:
np.matmul(k,w)

70

In [30]:
import numpy as np
s=np.arange(20)
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [32]:
print(s.size)


20


In [33]:
import numpy as np
k=np.array([1,2,3,4])
k


array([1, 2, 3, 4])

In [34]:
k.size*k.itemsize

16

In [40]:
import numpy as np
import sys
import time
d=range(5)
d


range(0, 5)

In [41]:
a=[1,2,3]
b=[4,5,6]
r=[(x,y) for x,y in zip(a,b)]
r

[(1, 4), (2, 5), (3, 6)]

In [42]:
n=np.array([1,2,3,4,5,6])
n.size

6

In [43]:
n.itemsize

4

In [50]:
n.shape

(6,)

In [51]:
n.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
n.reshape(3,2) #n.reshape([3,2])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [59]:
n=np.array([1,2,3,4,5,6])
n[1:5]


array([2, 3, 4, 5])

In [73]:
import  numpy as np
s=np.array([[1,2,3,4],[5,6,7,8]])
s.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [74]:
s[0:3]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [75]:
s[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [76]:
s[0:,3]

array([4, 8])

In [78]:
s[0:,2]

array([3, 7])

In [86]:
s[0:,1]

array([2, 6])

In [87]:
import  numpy as np
s=np.array([(1,2,3,4),(5,6,7,8), (10,11,12,13)])
s

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [88]:
import  numpy as np
s=np.array([[1,2,3,4],[5,6,7,8], [10,11,12,13]])
s

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [90]:
s[0:2]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [91]:
s[0:1]

array([[1, 2, 3, 4]])

In [92]:
s[0:1,2] #here 1 is repersents howmany rows to print. 2 represents skip


array([3])

In [95]:
s[0:2,3]


array([4, 8])

In [96]:
s[1:2,3]

array([8])

In [98]:
s[0:3,3]

array([ 4,  8, 13])

In [100]:
s[0:2,3]

array([4, 8])

In [101]:
s[1:3,3]

array([ 8, 13])

In [107]:
import numpy as np
a=np.linspace(1,3,15)   #15 elements range 3 
print(a)

[1.         1.14285714 1.28571429 1.42857143 1.57142857 1.71428571
 1.85714286 2.         2.14285714 2.28571429 2.42857143 2.57142857
 2.71428571 2.85714286 3.        ]


In [108]:
import numpy as np
a=np.linspace(1,2,3)   #15 elements range 3 
a

array([1. , 1.5, 2. ])

In [112]:
import numpy as np
a=np.array((1,2,3))
a.sum()

1

In [113]:
a.min()


1

In [114]:
a.max()


3

In [116]:
a=np.array([(1,2,3),(4,5,6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [119]:
a.sum(axis=0) 

array([5, 7, 9])

In [120]:
a.sum(axis=1)  # sum of the  each row


array([ 6, 15])

In [122]:
np.sqrt(a)


array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [123]:
np.std(a)

1.707825127659933

In [125]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [126]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [127]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([4,6,7,8])
np.hstack((a,b))

array([1, 2, 3, 4, 4, 6, 7, 8])

In [128]:
a.ravel()


array([1, 2, 3, 4])

In [133]:
a=np.array([[1,2,3,4],[6,3,8,9]])
a.ravel()

array([1, 2, 3, 4, 6, 3, 8, 9])

In [135]:
a.size


8

In [138]:
a.itemsize


4

In [139]:
a.sum()

36

In [143]:
import numpy as np
import matplotlib.pyplot as plt
x=np.arange(0,3*np.pi,0.1)
y=np.sin(x)

In [145]:
a=np.array((1,2,3))
np.exp(a)


array([ 2.71828183,  7.3890561 , 20.08553692])

In [146]:
np.log(a)  # base e


array([0.        , 0.69314718, 1.09861229])

In [147]:
np.log10(a)   # base 10

array([0.        , 0.30103   , 0.47712125])

In [154]:
a.size

3

In [155]:
a.itemsize

4

In [1]:
a==np.array([[1,2,3,4],[6,3,8,9]])
np.round(a)

NameError: name 'a' is not defined

In [9]:
# Random vector
import numpy as np
np.random.rand(5)

array([0.72571579, 0.25109357, 0.47156817, 0.07966408, 0.81438886])

In [8]:
# Random matrix
np.random.randn(2, 3) # rand vs. randn - what's the difference?

array([[ 0.46455712, -0.21264284,  1.91003421],
       [-0.62821488, -0.077066  , -0.39606434]])

In [5]:
# Random matrix
np.random.randn(2) # rand vs. randn - what's the difference?

array([0.87113781, 0.52049224])

In [2]:
import numpy as np
a=np.ones((2,2),dtype=int)
a


array([[1, 1],
       [1, 1]])

In [3]:
import numpy as np
a=np.zeros((3,2))
a


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

 import numpy as np
a=np.full((2,2),3,dtype=int)
a


In [5]:
import numpy as np
a=np.full((2,2),3,dtype=int)
a


array([[3, 3],
       [3, 3]])

In [14]:
import numpy as np
a=np.array([3,45,7,1,5])
#b=np.flip(a)# to reverse an array
#B
v=a[::-1]
v

array([ 5,  1,  7, 45,  3])

In [20]:
import numpy as np
a=np.repeat([3],5,axis=0)
a


array([3, 3, 3, 3, 3])

In [21]:
a=np.repeat([[4,3]],5,axis=1)
a

array([[4, 4, 4, 4, 4, 3, 3, 3, 3, 3]])

In [22]:
a=np.repeat([[4,3]],5,axis=0)
a

array([[4, 3],
       [4, 3],
       [4, 3],
       [4, 3],
       [4, 3]])

In [27]:
import  numpy as np
a=np.array([1,3,5,7,9,0])
b=np.array([2,12,5,6,8])
c=np.concatenate([a,b]) #c=np.concatenate([a,b],axis=0)
c
#d=np.hstack([a,b])
#e=np.vstack([a,b])

array([ 1,  3,  5,  7,  9,  0,  2, 12,  5,  6,  8])

In [32]:
import  numpy as np
a=np.array([1,3,5,7,9,0])
b=np.array([2,12,5,6,8])
r=np.r_[a,b]   #r _statement
r

array([ 1,  3,  5,  7,  9,  0,  2, 12,  5,  6,  8])

In [34]:
import numpy as np
a=np.array([1,2,3,4,5]) #power function
b=np.power(a,[2])
b

array([ 1,  4,  9, 16, 25])

In [35]:
c=np.power(a,[1,3,4,2,2])  #providing difefrent powers to all the elements in ana rray
c

array([ 1,  8, 81, 16, 25])

In [40]:
import numpy as np
a=np.array([1,5,8,7])
b=np.array([2,7,3,5])
d=np.diff(a)
d


array([ 4,  3, -1])

In [41]:
d1=np.diff(b)
d1

array([ 5, -4,  2])

In [42]:
df=np.diff([a,b])
df

array([[ 4,  3, -1],
       [ 5, -4,  2]])

In [43]:
e=np.diff([a,b],axis=0)
e

array([[ 1,  2, -5, -2]])

In [44]:
e=np.diff([a,b],axis=1)
e

array([[ 4,  3, -1],
       [ 5, -4,  2]])

In [52]:
import numpy as np
a=np.array([1,2])
b=np.array([3,4])  #cross product of two arrays of vectorsum
#cross means 1*4-3*2
c=np.cross(a,b)
c

array(-2)

In [60]:
import numpy as np
a=np.array([4,9,2,5])
c=np.sort(a)
c

array([2, 4, 5, 9])

In [58]:
import numpy as np
a=np.array([4,9,2,5])
b=np.array([5,7,12,8])
s=np.sort((a,b),axis=0)
s

array([[ 4,  7,  2,  5],
       [ 5,  9, 12,  8]])

In [59]:
import numpy as np
a=np.array([4,9,2,5])
b=np.array([5,7,12,8])
s=np.sort((a,b),axis=1)
s

array([[ 2,  4,  5,  9],
       [ 5,  7,  8, 12]])

In [63]:
import numpy as np
a=np.array([4,9,2,5])
b=np.array([5,7,12,8])
d=np.array([a,b])
d.flatten()
d

array([[ 4,  9,  2,  5],
       [ 5,  7, 12,  8]])

In [66]:
import numpy as np
a=[4,9,2,5]
b=[5,7,12,8]
d=np.array([a,b])
d.flatten("F")
d

array([[ 4,  9,  2,  5],
       [ 5,  7, 12,  8]])

In [68]:
import numpy as np
a=[4,9,2,5]
b=[5,7,12,8]
t=np.array([a,b])
t.flatten("C")
t

array([[ 4,  9,  2,  5],
       [ 5,  7, 12,  8]])

In [1]:
import numpy as np

a=np.array([4,9,2,5])
b=a[2]+a[3]
b

7

In [4]:
#accessing 2-D array elements
import numpy as np
a=np.array([[4,9,2,5],[5,7,12,8]])
c=a[0,1]
#d=a[1,2]
c
#d

9

In [10]:
#Import the numpy package under the name np (★☆☆)

import numpy as np

In [11]:
#2. Print the numpy version and the configuration 
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/sreekar/Library/include
    lib directory: C:/sreekar/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1868282989520
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
    cpu: x86_64
    endian: li

In [ ]:
#3. Create a null vector of size 10
import numpy as np
null_vector=np.ones(10)#we mat take anything either ones or zeros or eye etc.but size=10
null_vector

In [ ]:
#4. How to find the memory size of any array (★☆☆
null_vector.size

In [ ]:
#
5. How to get the documentation of the numpy add function from the command line? (★☆☆
                       #"help" fun.is a built-in ppythonfun.it provides documention for any obj.
help(np.add)                                                           

In [ ]:
#6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
import numpy as np
null=np.zeros(10)
null



In [ ]:
null[4]=1
null

In [ ]:
#7. Create a vector with values ranging from 10 to 49 (★☆☆
r=np.arange(10,50)
r

In [ ]:
#8. Reverse a vector (first element becomes last) (★☆☆)
import numpy as np
a=np.array([1,2,3,4,5])
"""res=np.flip(a)
res"""
#r=a[::-1]
#r
b=list(a)
b.reverse()
r=np.array(b)
r

In [ ]:
#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
import numpy as np
a=np.arange(0,8).reshape(3,3)
a
"""a=a.reshape(3,3)
a"""

In [ ]:
#10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
import numpy as np
a=np.array([1,2,0,0,4,0])
b=list(a)
res=[]
"""res=np.nonzero(a)
res"""
for i  in b:
    if i!=0:
        res.append(i)
print(res)

In [ ]:
#11. Create a 3x3 identity matrix (★☆☆)
import numpy as np
a=np.eye(3)
a

In [ ]:
#12. Create a 3x3x3 array with random values (★☆☆)
import numpy as np
a=np.random.rand(3,3)
a

In [ ]:
#13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
import numpy as np
a=np.random.rand(10,10)
a
b=a.min()
b
c=a.max()
c

In [ ]:
#14. Create a random vector of size 30 and find the mean value (★☆☆)
import numpy as np
n=np.random.random(30)
m=n.mean()
m


In [ ]:
#15. Create a 2d array with 1 on the border and 0 inside (★☆☆
import numpy as np
a=np.ones((2,2))
a[1:-1,1:-1]=0
a

In [ ]:
#16. How to add a border (filled with 0's) around an existing array? (★☆☆)
import numpy as np
a=np.ones((4,4))
a=np.pad(a,pad_width=1)
a

In [ ]:
#18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
import numpy as np
a=np.zeros((5,5))
a=np.diag([1,2,3,4])
a

In [ ]:
#
19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
import numpy as np
a=np.ones((8,8))


In [ ]:
#20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element
import numpy as np
a=np.unravel_index(100-1,(6,7,8))
#we can use /"unravel_index" to fond the nth element index in matrix
a

In [ ]:
#21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
import numpy as np
a=np.tile((8,8),dtype=int)
a

In [ ]:
#22. Normalize a 5x5 random matrix (★☆☆)
import  numpy as np
a=np.random.random((5,5))
a=(a-np.mean(a))/np.std(a)
a

In [ ]:
#24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
import numpy as np
a=np.ones((5,3),dtype=int)
b=np.ones((3,2),dtype=int)
#c=a@b
c=np.dot(a,b)
c